version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: ewallet-user-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - ewallet-network

  wallet-service:
    build: ./wallet-service
    container_name: ewallet-wallet-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    networks:
      - ewallet-network
    depends_on:
      - user-service

  transaction-service:
    build: ./transaction-service
    container_name: ewallet-transaction-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - ewallet-network
    depends_on:
      - user-service
      - wallet-service
      - notification-service

  notification-service:
    build: ./notification-service
    container_name: ewallet-notification-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
    networks:
      - ewallet-network

  api-gateway:
    build: ./api-gateway
    container_name: ewallet-api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - ewallet-network
    depends_on:
      - user-service
      - wallet-service
      - transaction-service
      - notification-service

networks:
  ewallet-network:
    driver: bridge
